cc_test(
    name = "vector_test",
    srcs = ["vector_test.cc"],
    deps = [
        "//vector:vector",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "string_test",
    srcs = ["string_test.cc"],
    deps = [
        "//string:string",
        "@googletest//:gtest_main",
    ],
)
