cc_test(
    name = "vector_test",
    srcs = ["vector_test.cc"],
    deps = [
        "//vector:vector",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "string_test",
    srcs = ["string_test.cc"],
    deps = [
        "//string:string",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "functors_test",
    srcs = ["functors_test.cc"],
    deps = [
        "//functors:functors",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "unique_ptr_test",
    srcs = ["unique_ptr_test.cc"],
    deps = [
        "//unique_ptr:unique_ptr",
        "@googletest//:gtest_main",
    ],
)
